import 'package:flutter/material.dart';
import 'snake_cursor.dart';
import 'snake_copilot.dart';
import 'snake_aider_ui.dart';

void main() {
  runApp(const MainApp());
}

class MainApp extends StatelessWidget {
  const MainApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Snake Games',
      theme: ThemeData(
        primarySwatch: Colors.green,
        useMaterial3: true,
      ),
      home: const SnakeGamesHome(),
    );
  }
}

class SnakeGamesHome extends StatefulWidget {
  const SnakeGamesHome({super.key});

  @override
  State<SnakeGamesHome> createState() => _SnakeGamesHomeState();
}

class _SnakeGamesHomeState extends State<SnakeGamesHome> with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Snake Games Collection'),
        bottom: TabBar(
          controller: _tabController,
          tabs: const [
            Tab(text: 'Cursor'),
            Tab(text: 'Aider'),
            Tab(text: 'Copilot'),
          ],
        ),
      ),
      body: TabBarView(
        controller: _tabController,
        children: [
          // Cursor implementation
          Stack(
            children: [
              const SnakeCursor(),
              Positioned(
                top: 8,
                right: 8,
                child: Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: Colors.black54,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Text(
                    'Generated by Cursor',
                    style: TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
            ],
          ),
          
          // Aider implementation
          Stack(
            children: [
              const SnakeAiderUI(),
              Positioned(
                top: 8,
                right: 8,
                child: Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: Colors.black54,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Text(
                    'Generated by Aider',
                    style: TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
            ],
          ),
          
          // Copilot implementation
          Stack(
            children: [
              const SnakeGameScreen(),
              Positioned(
                top: 8,
                right: 8,
                child: Container(
                  padding: const EdgeInsets.all(8),
                  decoration: BoxDecoration(
                    color: Colors.black54,
                    borderRadius: BorderRadius.circular(8),
                  ),
                  child: const Text(
                    'Generated by Copilot',
                    style: TextStyle(
                      color: Colors.white,
                      fontWeight: FontWeight.bold,
                    ),
                  ),
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}
