include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print: true
    - prefer_single_quotes: true
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - avoid_empty_else: true
    - avoid_relative_lib_imports: true
    - avoid_redundant_argument_values: true
    - avoid_unnecessary_containers: true
    - directives_ordering: true
    - prefer_if_null_operators: true
    - prefer_spread_collections: true
    - sort_child_properties_last: true
    - unnecessary_const: true
    - unnecessary_late: true
    - unnecessary_null_checks: true
    - use_build_context_synchronously: true