name: todo_app
description: A modern to-do list application with advanced features.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1          # For state management
  hive: ^2.2.3              # For local storage
  hive_flutter: ^1.1.0      # Flutter integration for Hive
  uuid: ^4.2.1              # For generating unique IDs
  intl: ^0.18.1             # For date formatting
  flutter_slidable: ^3.0.1  # For swipe actions on task items

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1    # For Hive type generation
  build_runner: ^2.4.6      # For code generation

flutter:
  uses-material-design: true